### ISSUE TITLE
Publish as NPM

### ISSUE THREAD

**Issue by KasperAndersson** [nglar/ngTouch#14]
https://docs.npmjs.com/getting-started/publishing-npm-packages

**Comment by aliirz** [comment]
I already added the necessary stuff to publish it as a package here: https://github.com/nglar/ngTouch/blob/master/package.json

Also the steps to publish it as a bower package have been taken care of.

@marktopper can you go ahead and publish it as a npm and bower package both?

**Comment by aliirz** [comment]
my bad. its already published as a bower package

**Comment by marktopper** [comment]
Sorry the delay, I will add this as soon as I get the time.

**EDIT:** I think I have time doing the weekend. Anyways, I will keep you updated. Happy Halloween :jack_o_lantern:

**Comment by KasperAndersson** [comment]
@marktopper @aliirz Nice one guys, thanks and you too. (Not celebrating it here in DK)

**Comment by marktopper** [comment]
@KasperAndersson We do at my group of friends. But yea, it is not normal to do in Denmark.

Anyways, I have published the package to [npmjs](https://npmjs.org).

You can now install it using `npm install ngtouch`.

**EDIT:** Here is the link: https://www.npmjs.com/package/ngtouch

**Comment by aliirz** [comment]
:bow:

**Comment by marktopper** [comment]
@aliirz Whats wrong?

**Comment by KasperAndersson** [comment]
Great thanks @marktopper, have a great party.

**Comment by bmccutchon** [comment]
@marktopper Until I found this issue, I didn't know the project was published to npm. Could you add it to the README for this project, ng-touchmove, etc.?

**Comment by marktopper** [comment]
I'll go ahead and add that right away @McBrainy.

EDIT: Added to the documentation.
