### ISSUE TITLE
Links without ng-touch... aren't working on touch-devices

### ISSUE THREAD

**Issue by Esger** [nglar/ngTouch#17]
Using ng-touch, normal links with href attribute and no ng-touch/angular attributes don't work no more on touch devices. (they do respond to a mouse click)
I have ng-touchmove and ng-touchend attributes on the body element. If I remove these, my links work again.
To show the problem I put my project here: http://ashware.nl/pentomino/ngtouchproblem/ try tapping the link to my website (ashWare) at the bottom right.
https://github.com/Esger/Pentominos

**Comment by marktopper** [comment]
It will overwrite a link and will not be changed.
